In [2]:
import pandas as pd
import json

In [3]:
df = pd.read_csv('../Data/processed/Viz_df.csv')
df

,id,Episode_Title,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Guest_Popularity_missing,Listening_Time_minutes,prediction,Genre,Publication_day_number,Publication_day,Publication_time_hour,Publication_time,Podcast_Name
0,202844,30,119.97,64.21,17.93,0.0,Negative,0,57.67601,99.824983,Sports,5,Saturday,1,Night,Game Day
1,110926,57,62.57,27.22,50.84,1.0,Positive,0,48.82398,47.413588,Lifestyle,4,Friday,9,Morning,Lifestyle Lounge
2,200533,93,99.12,82.95,93.62,1.0,Negative,0,82.95502,76.563204,News,1,Tuesday,9,Morning,World Watch
3,285483,30,91.05,99.51,13.44,3.0,Neutral,0,71.68635,70.170154,Sports,3,Thursday,20,Evening,Sports Central
4,79612,26,61.42,23.48,5.69,1.0,Negative,0,50.45880,50.319279,Lifestyle,0,Monday,15,Afternoon,Fashion Forward
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599993,259180,86,63.41,20.34,67.59,2.0,Neutral,0,32.06549,37.200416,Music,6,Sunday,1,Night,Sound Waves
599994,365840,80,61.19,38.87,0.83,0.0,Neutral,0,53.73476,50.997901,Music,6,Sunday,9,Morning,Tune Time
599995,131933,55,19.40,39.77,52.85,1.0,Negative,0,13.09288,12.820011,Health,6,Sunday,9,Morning,Fitness First
599996,671157,69,17.51,92.29,57.35,0.0,Neutral,0,13.36094,12.357595,News,4,Friday,20,Evening,Daily Digest
599997,121959,53,54.11,53.40,22.20,3.0,Positive,0,29.30020,37.787504,Technology,1,Tuesday,20,Evening,Digital Digest

In [4]:
podcast_names = df.Podcast_Name.unique()

In [5]:
with open('./data/podcast_names.json', 'w') as f:
    json.dump(podcast_names.tolist(), f)

In [6]:
df.Episode_Length_minutes.mean()

np.float64(64.51463925737754)

In [7]:
df.Episode_Title.describe()

count    599998.000000
mean         51.425735
std          28.081941
min           1.000000
25%          28.000000
50%          52.000000
75%          75.000000
max         100.000000
Name: Episode_Title, dtype: float64

In [8]:
df.Host_Popularity_percentage.mean()

np.float64(59.84419946470655)

In [9]:
df.Number_of_Ads.describe()

count    599998.000000
mean          1.348176
std           1.152937
min           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
max         103.910000
Name: Number_of_Ads, dtype: float64

In [17]:
df.Genre.describe()

count     599998
unique        10
top       Sports
freq       70301
Name: Genre, dtype: object

In [10]:
genres = df.Genre.unique()
with open('./data/genres.json', 'w') as g:
    json.dump(genres.tolist(), g)

In [11]:
days = {
    'Monday': 0,
    'Tuesday': 1,
    'Wednesday': 2,
    'Thursday': 3,
    'Friday': 4,
    'Saturday': 5,
    'Sunday': 6
}

with open('./data/days.json', 'w') as f:
    json.dump(days, f)

In [12]:
publication_time = {
    'Morning': 9,
    'Afternoon': 15,
    'Evening': 20,
    'Night': 1
}

with open('./data/publication_time.json', 'w') as f:
    json.dump(publication_time, f)

In [13]:
encoded_df = pd.read_csv('../Data/processed/encoded_df.csv')
encoded_df

,id,Episode_Title,Episode_Length_minutes,Host_Popularity_percentage,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment,Guest_Popularity_missing,Genre_encoded,Listening_Time_minutes,Time_sin,Time_cos,Day_sin,Day_cos,Podcast_Encoded
0,202844,30,119.97,64.21,17.93,0.0,-1,0,44.913404,57.67601,0.258819,0.965926,-0.974928,-0.222521,43.980881
1,110926,57,62.57,27.22,50.84,1.0,1,0,45.440905,48.82398,0.707107,-0.707107,-0.433884,-0.900969,45.628020
2,200533,93,99.12,82.95,93.62,1.0,-1,0,44.371825,82.95502,0.707107,-0.707107,0.781831,0.623490,43.996397
3,285483,30,91.05,99.51,13.44,3.0,0,0,44.913404,71.68635,-0.866025,0.500000,0.433884,-0.900969,41.702596
4,79612,26,61.42,23.48,5.69,1.0,-1,0,45.440905,50.45880,-0.707107,-0.707107,0.000000,1.000000,45.239931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599993,259180,86,63.41,20.34,67.59,2.0,0,0,46.533255,32.06549,0.258819,0.965926,-0.781831,0.623490,44.461635
599994,365840,80,61.19,38.87,0.83,0.0,0,0,46.533255,53.73476,0.707107,-0.707107,-0.781831,0.623490,47.007739
599995,131933,55,19.40,39.77,52.85,1.0,-1,0,45.819181,13.09288,0.707107,-0.707107,-0.781831,0.623490,45.873295
599996,671157,69,17.51,92.29,57.35,0.0,0,0,44.371825,13.36094,-0.866025,0.500000,-0.433884,-0.900969,45.814585
599997,121959,53,54.11,53.40,22.20,3.0,1,0,45.723748,29.30020,-0.866025,0.500000,0.781831,0.623490,44.778224

In [31]:
lenght = 65
host_popularity = 60
guest_popularity = 52.51  # Average Popularity when no guest is present
missing_guest = 1
podcast = 'Game Day'
title = 1
genre = 'News'
ads = 1
sentiment_raw = 'Neutral'
publication_day = 2
publication_time = 12

In [15]:
sentiment_map = {
    'Negative': -1,
    'Neutral': 0,
    'Positive': 1
}

sentiment = sentiment_map[sentiment_raw]

In [16]:
sentiment

0

In [ ]:
genre_map = {
    'Business': 45.55244226723161,
    'Comedy': 44.48775637598833,
    'Education': 45.69957544537044, 
    'Health': 45.81918055381969, 
    'Lifestyle': 45.4409049194452, 
    'Music': 46.533255061929985, 
    'News': 44.37182458341537, 
    'Sports': 44.913403840628156, 
    'Technology': 45.72374847377965, 
    'True Crime': 45.99179846445972 
}

In [33]:
import numpy as np

# Encoding for  hours (0-23)
Time_sin = np.sin(2 * np.pi * publication_time / 24)
Time_cos = np.cos(2 * np.pi * publication_time / 24)

# encoding for days (0-6)
Day_sin = np.sin(2 * np.pi * publication_day / 7)
Day_cos = np.cos(2 * np.pi * publication_day / 7)

In [34]:
print(Time_sin, Time_cos, Day_sin, Day_cos)

1.2246467991473532e-16 -1.0 0.9749279121818236 -0.22252093395631434